### ISSUE TITLE
Adding MME-RealWorld to lmms-eval

### ISSUE THREAD

**Issue by bfshi** [yfzhang114/MME-RealWorld#3]
It would be great to have support for MME-RealWorld in [lmms-eval](https://github.com/EvolvingLMMs-Lab/lmms-eval), one of the commonly used benchmark suite by lots of researchers.

**Comment by yfzhang114** [comment]
Thank you for your suggestion! We will reach out to lmms-eval soon and work towards adding support for MME-RealWorld in the benchmark.

**Comment by yfzhang114** [comment]
> It would be great to have support for MME-RealWorld in [lmms-eval](https://github.com/EvolvingLMMs-Lab/lmms-eval), one of the commonly used benchmark suite by lots of researchers.

MME-RealWorld is now supported by lmms-eval! Feel free to use it without hesitation!

**Comment by bfshi** [comment]
That’s great news! Thank you for the effort!
