### ISSUE TITLE
数据集数据对不齐

### ISSUE THREAD

**Issue by max-yue** [yfzhang114/MME-RealWorld#6]
blog https://video-mme.github.io/home_page.html 说英文 29,429 QA pairs， 中文 5,917 QA pairs；
排行榜 https://video-mme.github.io/home_page.html  说 23599 条
hf 数据集 yifanzhang114/MME-RealWorld-Base64 上是 23609 条

原因是啥呀？

**Comment by yfzhang114** [comment]
因为有一些中文的问题比较模糊，图像中出现了英文，上传时将这几十条数据归到了en里面，不过我们测试过，基本上不会对性能造成影响
